DELETE http://localhost:3001/api/persons/1

/*
- Projektin juureen hakemisto requests, 
jonka sisään talletetaan REST Client -pyynnöt .rest-päätteisinä tiedostoina.
- Kaikki muistiinpanot hakeva pyynnön määrittelevä tiedosto get_all_notes.rest
*/

/*
Klikkaamalla tekstiä Send Request, REST client suorittaa määritellyn HTTP-pyynnön, 
ja palvelimen vastaus avautuu editoriin.
*/
